declare var gg_rct_Fence_Zone: rect;
declare var gg_rct_Round_1: rect;
declare var gg_rct_Round_2: rect;
declare var gg_rct_Round_3a: rect;
declare var gg_rct_Round_3b: rect;
declare var gg_rct_Round_4: rect;
declare var gg_rct_Round_5: rect;
declare var gg_rct_Round_6: rect;
declare var gg_rct_Round_7: rect;
declare var gg_rct_Round_8: rect;
declare var gg_rct_Round_9: rect;
declare var gg_rct_Round_10: rect;
declare var gg_rct_Round_11: rect;
declare var gg_rct_Round_12: rect;
declare var gg_rct_Round_13: rect;
declare var gg_rct_Round_14: rect;
declare var gg_rct_Round_15: rect;
declare var gg_rct_Round_16: rect;
declare var gg_rct_Round_17: rect;
declare var gg_rct_Dummy: rect;
declare var gg_rct_Entire_Map: rect;
declare var gg_trg_Initiate: trigger;
declare var gg_trg_Preload: trigger;
declare var gg_trg_Host: trigger;
declare var gg_trg_Transfer: trigger;
declare var gg_trg_Reset_Game: trigger;
declare var gg_trg_Initial_Timer: trigger;
declare var gg_trg_Leaderboard: trigger;
declare var gg_trg_Setup_Timer_Expire: trigger;
declare var gg_trg_Modify_Time: trigger;
declare var gg_trg_Modify_Difficulty: trigger;
declare var gg_trg_Modify_Saving: trigger;
declare var gg_trg_Dialog_Click: trigger;
declare var gg_trg_Test: trigger;
declare var gg_trg_Cancel: trigger;
declare var gg_trg_Hide_Items: trigger;
declare var gg_trg_Start: trigger;
declare var gg_trg_Remove_Out_Of_Bounds_Missiles: trigger;
declare var gg_trg_Remove_Attack: trigger;
declare var gg_trg_New_Round: trigger;
declare var gg_trg_End_Round: trigger;
declare var gg_trg_Round_Setup: trigger;
declare var gg_trg_Round_10: trigger;
declare var gg_trg_Unit_Movement: trigger;
declare var gg_trg_Unit_Extra_Movement: trigger;
declare var gg_trg_Sheep_Dies: trigger;
declare var gg_trg_Sheep_Revive: trigger;
declare var gg_trg_Two_Hit_Save: trigger;
declare var gg_trg_Summon_Golem: trigger;
declare var gg_trg_Golem_Enters: trigger;
declare var gg_trg_Weaken_9_11_12_13_14: trigger;
declare var gg_trg_Zombie_Remove: trigger;
declare var gg_trg_Zombie_Stream: trigger;
declare var gg_trg_Mass_Link: trigger;
declare var gg_trg_Swarm: trigger;
declare var gg_trg_Shuriken: trigger;
declare var gg_trg_Ice_Leap: trigger;
declare var gg_trg_Natural_Relocation: trigger;
declare var gg_trg_Archmage: trigger;
declare var gg_trg_Firebolt: trigger;
declare var gg_trg_Teleport: trigger;
declare var gg_trg_Mirror_Images: trigger;
declare var gg_trg_Axemaster: trigger;
declare var gg_trg_Bladestorm: trigger;
declare var gg_trg_Bladestorm_Move: trigger;
declare var gg_trg_Image_Enter: trigger;
declare var gg_trg_Thrust: trigger;
declare var gg_trg_Thrust_Rockets: trigger;
declare var gg_trg_Lightning_Line: trigger;
declare var gg_trg_Stampede: trigger;
declare var gg_trg_Stampede_Move: trigger;
declare var gg_trg_Goblin_Rocket_Spray: trigger;
declare var gg_trg_Homing_Jump: trigger;
declare var gg_trg_Homing_Move: trigger;
declare var gg_trg_Homing_Effect: trigger;
declare var gg_trg_Homing_End: trigger;
declare var gg_trg_Bomber: trigger;
declare var gg_trg_Hunter_Rocket: trigger;
declare var gg_trg_Glaive_Thrower: trigger;
declare var gg_trg_Glaive_Thrower_Spill: trigger;
declare var gg_trg_Catapult: trigger;
declare var gg_trg_Invunerability: trigger;
declare var gg_trg_Antirun: trigger;
declare var gg_trg_Win: trigger;
declare var gg_trg_Lose: trigger;
declare var gg_trg_Begin_New_Game: trigger;
declare var gg_trg_End: trigger;
declare var gg_trg_Remove_Items: trigger;
declare var gg_trg_Z_Toggle: trigger;
declare var gg_trg_Destroy_Command: trigger;
declare var gg_trg_Destroy_Last: trigger;
declare var gg_trg_FC_Plus_GUI: trigger;
declare var gg_trg_Destroy_GUI: trigger;
declare var gg_trg_FC_Minus_GUI: trigger;
declare var gg_trg_Remove_From_Cancel: trigger;
declare var gg_trg_Zoom: trigger;
declare var gg_trg_Periodic_Zoom: trigger;
declare var gg_trg_Autozoom: trigger;
declare var gg_trg_Give_Gold: trigger;
declare var gg_trg_Hide: trigger;
declare var gg_trg_Show: trigger;
declare var gg_trg_Give_Specific_Gold: trigger;
declare var gg_trg_Give_Control: trigger;
declare var gg_trg_Full_Control: trigger;
declare var gg_trg_Periodic_Gold: trigger;
declare var gg_trg_Saving_Farm: trigger;
declare var gg_trg_Fence_Zone: trigger;
declare var gg_trg_Computer_Share: trigger;
declare var gg_trg_Player_Leaves: trigger;
declare var gg_trg_Research: trigger;
declare var gg_trg_Reset: trigger;
declare var gg_trg_Missile_Periodic: trigger;
declare var gg_trg_Collision_Reaction: trigger;
declare var gg_trg_Damage: trigger;
declare var gg_trg_Damage_Method_1_And_4: trigger;
declare var gg_trg_Drag: trigger;
declare var gg_trg_Link: trigger;
declare var gg_trg_After_Destination_1_to_6: trigger;
declare var gg_trg_After_Destination_Others: trigger;
declare var gg_trg_Fragment: trigger;
declare var udg_TempUnitGroup: group
declare var udg_FC: Array<number>
declare var udg_TempPoint: location
declare var udg_CancelGroup: group
declare var udg_Index: number
declare var udg_StartPoint: Array<location>
declare var udg_Angle: Array<number>
declare var udg_Missile: Array<unit> | null
declare var udg_DamageSource: Array<unit>
declare var udg_Jump: Array<boolean>
declare var udg_Teleportation: Array<number>
declare var udg_Distance: Array<number>
declare var udg_AttackType: Array<attacktype>
declare var udg_DamageMethod: Array<number>
declare var udg_ExplodeRadius: Array<number>
declare var udg_DamageSpecialEffect: Array<string>
declare var udg_LoopIndex: number
declare var udg_DamageSpecialEffectLocation: Array<string>
declare var udg_CollisionRadius: Array<number>
declare var udg_Damage: Array<number>
declare var udg_Targets: Array<number>
declare var udg_TargetsAdvanced: Array<number>
declare var udg_Drag: Array<boolean>
declare var udg_Link: Array<boolean>
declare var udg_Lightning: Array<boolean>
declare var udg_LightningEffect: Array<lightning>
declare var udg_Speed: Array<number>
declare var udg_VerticalArc: Array<number>
declare var udg_HorizontalArc: Array<number>
declare var udg_MissileEffectString: Array<string>
declare var udg_MissileEffect: Array<effect>
declare var udg_MissileSize: Array<number>
declare var udg_TerrainReaction: Array<number>
declare var udg_TreeReaction: Array<number>
declare var udg_BoundaryReaction: Array<number>
declare var udg_BuildingReaction: Array<number>
declare var udg_AfterDestination: Array<number>
declare var udg_IndexReseter: number
declare var udg_AfterLinkDeath: Array<number>
declare var udg_TempPoint2: location
declare var udg_TempPoint3: location
declare var udg_XYZ: Array<number>
declare var udg_TempGroup: group
declare var udg_AlreadyHit: Array<group>
declare var udg_TempGroup2: group
declare var udg_Sheep: force
declare var udg_Player: Array<player>
declare var udg_PlayerColor: Array<string>
declare var udg_ControlBoolean: Array<boolean>
declare var udg_Spirit: force
declare var udg_RoundInfo: Array<number>
declare var udg_NewRoundTimer: timer
declare var udg_RoundTimer: timer
declare var udg_TimeModifier: number
declare var udg_RoundRegion: Array<rect>
declare var udg_InitialTimer: timer
declare var udg_Dialog: dialog
declare var udg_Button: Array<button>
declare var udg_Revives: Array<number>
declare var udg_SaveGroup: force
declare var udg_String_Round: Array<string>
declare var udg_Income: Array<number>
declare var udg_EscToggle: Array<boolean>
declare var udg_HomingAngle: number
declare var udg_TempGroup3: group
declare var udg_IceAngle: Array<number>
declare var udg_TurnSpeed: number
declare var udg_HomingEffect: Array<effect>
declare var udg_RobotTimer: timer
declare var udg_TipString: Array<string>
declare var udg_Continue: Array<number>
declare var udg_StampedeSpeed: Array<number>
declare var udg_StampedeUnit: Array<unit>
declare var udg_TimeLasted: number
declare var udg_SetupString: Array<string>
declare var udg_SaveString: string
declare var udg_HomingUnit: unit
declare var udg_TempPoint4: location
declare var udg_XHashtable: hashtable
declare var udg_TempUnit: unit
declare var udg_BladeGroup: group
declare var udg_TempInt: number
declare var udg_Host: player
declare var udg_HasBounced: Array<boolean>
declare var udg_TempReal: number
declare var udg_Upgrades: Array<number>
declare var udg_TempReal2: number
declare var udg_TempPlayer: player
declare var udg_TempUnitType: number
declare var udg_TempInt2: number
declare var udg_FarmCount: Array<number>
declare var udg_TempUnit2: unit
declare var udg_Untitled_Variable_001: number
declare var gg_unit_n007_0048: unit
